#!/bin/bash

#cat读取文件内容的一般写法是：
#cat file1 file2 file3...
#这个命令将作为命令行参数的文件内容拼接在一起

#cat命令不仅可以读取文件， 拼接文件，还能从标准输入中进行读取

#从标准输入中读取需要使用管道操作符

echo 'Text through stdin' | cat - file.txt


#在上边的代码中，- 被作为stdin文本的文件名

#cat摆脱多余的空白行
#cat -s file  压缩相邻的空白行

#将制表符显示为^I
# cat -T file.py

#行号，使用cat命令的-n参数会在输出的每一个行内容之前加上行号
