#!/bin/bash

#利用script和scriptreplay命令。我们可以录制命令的次序以及时序，将相关数据记录在在文本文件中
#利用这些文件，其他人可以在终端回放并查看命令的输出

script -t 2> timing.log -a output.seesion

#两个配置文件被当做script命令的参数，其中一个文件timing.log用于存储时序信息，描述每一个命令在何
时运行;另一个文件output.session用于存储命令输出

#-t选项用于将时序数据导入stderr  2>则用于将stderr重定向到timing.log

#可以按照下面的这方法回放命令执行过程：

scriptreplay timing.log output.session

